In [4]:
import tensorflow as tf
import numpy as np

In [88]:
a = tf.constant(np.arange(12,dtype=np.int32), shape=[2,2,3])
b = tf.constant(10*np.arange(12, dtype=np.int32), shape=[2,3,2])
c = tf.constant(np.ones(2,dtype=np.int32), shape=[10,1,2])
d = tf.constant(np.ones((10,2,6), dtype=np.int32))

In [89]:
sess = tf.InteractiveSession()

In [90]:
sess.run(a)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=int32)

In [91]:
sess.run(b)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]], dtype=int32)

In [92]:
sess.run(c)

array([[[1, 1]],

       [[1, 1]],

       [[1, 1]],

       [[1, 1]],

       [[1, 1]],

       [[1, 1]],

       [[1, 1]],

       [[1, 1]],

       [[1, 1]],

       [[1, 1]]], dtype=int32)

In [93]:
sess.run(d)

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]], dtype=int32)

In [94]:
sess.run(tf.matmul(c,d))

array([[[2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2]]], dtype=int32)

In [166]:
ff = np.arange(15)

In [167]:
x,y,z = (25,ff.shape[0],35)

In [197]:
T = tf.constant(np.arange(2*z*y ,dtype=np.int32), shape=[2*z,y])
TT = tf.constant(np.arange(2*z*y ,dtype=np.int32), shape=[y,z*2])

In [193]:
f = tf.constant(np.stack(z*[ff],axis=0).astype(np.int32), shape=[z,1,y])

In [194]:
T.get_shape().as_list()

[70, 15, 25]

In [195]:
f.get_shape().as_list()

[35, 1, 15]

In [198]:
m = tf.matmul(TT,T)

In [174]:
sess.run(T)

array([[[    0,     1,     2, ...,    22,    23,    24],
        [   25,    26,    27, ...,    47,    48,    49],
        [   50,    51,    52, ...,    72,    73,    74],
        ...,
        [  300,   301,   302, ...,   322,   323,   324],
        [  325,   326,   327, ...,   347,   348,   349],
        [  350,   351,   352, ...,   372,   373,   374]],

       [[  375,   376,   377, ...,   397,   398,   399],
        [  400,   401,   402, ...,   422,   423,   424],
        [  425,   426,   427, ...,   447,   448,   449],
        ...,
        [  675,   676,   677, ...,   697,   698,   699],
        [  700,   701,   702, ...,   722,   723,   724],
        [  725,   726,   727, ...,   747,   748,   749]],

       [[  750,   751,   752, ...,   772,   773,   774],
        [  775,   776,   777, ...,   797,   798,   799],
        [  800,   801,   802, ...,   822,   823,   824],
        ...,
        [ 1050,  1051,  1052, ...,  1072,  1073,  1074],
        [ 1075,  1076,  1077, ...,  1097,  10

In [175]:
sess.run(f)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,

In [176]:
sess.run(m)

array([[[  25375,   25480,   25585,   25690,   25795,   25900,   26005,
           26110,   26215,   26320,   26425,   26530,   26635,   26740,
           26845,   26950,   27055,   27160,   27265,   27370,   27475,
           27580,   27685,   27790,   27895]],

       [[  64750,   64855,   64960,   65065,   65170,   65275,   65380,
           65485,   65590,   65695,   65800,   65905,   66010,   66115,
           66220,   66325,   66430,   66535,   66640,   66745,   66850,
           66955,   67060,   67165,   67270]],

       [[ 104125,  104230,  104335,  104440,  104545,  104650,  104755,
          104860,  104965,  105070,  105175,  105280,  105385,  105490,
          105595,  105700,  105805,  105910,  106015,  106120,  106225,
          106330,  106435,  106540,  106645]],

       [[ 143500,  143605,  143710,  143815,  143920,  144025,  144130,
          144235,  144340,  144445,  144550,  144655,  144760,  144865,
          144970,  145075,  145180,  145285,  145390,  145495,  

In [177]:
m.get_shape()

TensorShape([Dimension(35), Dimension(1), Dimension(25)])

In [203]:
bs = 5
numFeat = 10

In [204]:
batch = np.array([b*np.ones(numFeat) for b in range(bs)])

In [205]:
batch

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [ ]:
T = 